### ISSUE TITLE
pub finished with exit code 255

### ISSUE THREAD

**Issue by francyfre** [lohanidamodar/flutter_automation#3]
i follow your Flutter Complete App From Scratch with Firebase.
When i need to use flutter_automation:   and run flutter pub run flutter_automation -f in terminal  go out to me: 
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
pub finished with exit code 255

and create only home.dart file!! 
I cannot go out alone for that problem... somebody can help me please?
thankYouALot
francyfre

**Comment by francyfre** [comment]
i add  import 'dart:async'; to my page.... but same errors!!!

**Comment by sekwtus** [comment]
can you fixed this error
