### ISSUE TITLE
Failed on firebase auth

### ISSUE THREAD

**Issue by johnareid54** [lohanidamodar/flutter_automation#6]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.804], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.2)
[√] Connected device (1 available)

[firebasetest] flutter pub get
Running "flutter pub get" in firebasetest...                    
Because firebase_auth >=1.0.1 depends on firebase_auth_web ^1.0.1 which depends on http_parser ^4.0.0, firebase_auth >=1.0.1 requires http_parser ^4.0.0.

And because http 0.12.2 depends on http_parser >=0.0.1 <4.0.0 and no versions of http match >0.12.2 <0.13.0, firebase_auth >=1.0.1 is incompatible with http ^0.12.2.

And because flutter_automation 1.4.0 depends on http ^0.12.2 and no versions of flutter_automation match >1.4.0 <2.0.0, firebase_auth >=1.0.1 is incompatible with flutter_automation ^1.4.0.

So, because firebasetest depends on both flutter_automation ^1.4.0 and firebase_auth ^1.0.1, version solving failed.
pub get failed (1; So, because firebasetest depends on both flutter_automation ^1.4.0 and firebase_auth ^1.0.1, version solving failed.)
exit code 1

**Comment by Aashishm178** [comment]
Can you please show me your pubspec.yaml file

**Comment by johnareid54** [comment]
pubspec.yaml file:

name: tester
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_automation: ^1.4.0

  firebase_auth: ^1.0.1
  provider: ^5.0.0
  google_sign_in: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

**Comment by Aashishm178** [comment]
Change your firebase auth to firebase_auth: ^0.20.0 might solve the problem

**Comment by johnareid54** [comment]
Bit of a nightmare!

[tester] flutter pub get
Running "flutter pub get" in tester...                          
Because google_sign_in >=5.0.0 depends on google_sign_in_platform_interface ^2.0.0 which depends on quiver ^3.0.0, google_sign_in >=5.0.0 requires quiver ^3.0.0.

And because firebase_auth >=0.20.0 <0.21.0-1.0.nullsafety.0 depends on firebase_core ^0.7.0 which depends on quiver ^2.0.0, google_sign_in >=5.0.0 is incompatible with firebase_auth >=0.20.0 <0.21.0-1.0.nullsafety.0.

So, because tester depends on both firebase_auth ^0.20.0 and google_sign_in ^5.0.0, version solving failed.
pub get failed (1; So, because tester depends on both firebase_auth ^0.20.0 and google_sign_in ^5.0.0, version solving failed.)
exit code 1

**Comment by Aashishm178** [comment]
Change google_sign_in to 4.5.6

**Comment by johnareid54** [comment]
Thanks that got rid of the cross pub calls, but the code sis not work:

PS C:\Users\john\Desktop\tester> flutter pub pub run flutter_automation --firebase-auth
upgraded to androidx
added dependencies
firebase auth implemented
CreateProcessW failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: cp -r C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_automation-1.4.0\bin\..\lib\auth_stock\lib .\
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:565:18)
#3      Process.run (dart:io-patch/process_patch.dart:47:12)
#4      _Commons.copyFilesRecursive (package:flutter_automation/commons.dart:75:13)
#5      _copyStockFiles (package:flutter_automation/firebase_auth.dart:84:12)
#6      _firebaseAuth (package:flutter_automation/firebase_auth.dart:12:3)
<asynchronous suspension>
#7      decipherScript (package:flutter_automation/flutter_automation.dart:71:5)
<asynchronous suspension>
pub finished with exit code 255

**Comment by Aashishm178** [comment]
Are you running the code in emulator ?

**Comment by johnareid54** [comment]
In VS code terminal window

**Comment by Aashishm178** [comment]
There is some problem copying the stock files.
I suggest you do flutter clean and flutter pub get again 
and run the command again.

**Comment by johnareid54** [comment]
I used power shell:

PS C:\WINDOWS> cd C:\Users\john\Desktop\tester1
PS C:\Users\john\Desktop\tester1> flutter clean
Deleting .dart_tool...                                               8ms
Deleting .packages...                                                2ms
Deleting Generated.xcconfig...                                       1ms
Deleting flutter_export_environment.sh...                            0ms
Deleting .flutter-plugins-dependencies...                            1ms
Deleting .flutter-plugins...                                         1ms
PS C:\Users\john\Desktop\tester1> flutter pub get
Running "flutter pub get" in tester1...                          1,073ms
PS C:\Users\john\Desktop\tester1> flutter pub pub run flutter_automation --firebase-auth
upgraded to androidx
added dependencies
firebase auth implemented
CreateProcessW failed 2
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: cp -r C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_automation-1.4.0\bin\..\lib\auth_stock\lib .\
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:565:18)
#3      Process.run (dart:io-patch/process_patch.dart:47:12)
#4      _Commons.copyFilesRecursive (package:flutter_automation/commons.dart:75:13)
#5      _copyStockFiles (package:flutter_automation/firebase_auth.dart:84:12)
#6      _firebaseAuth (package:flutter_automation/firebase_auth.dart:12:3)
<asynchronous suspension>
#7      decipherScript (package:flutter_automation/flutter_automation.dart:71:5)
<asynchronous suspension>
pub finished with exit code 255
PS C:\Users\john\Desktop\tester1>
