### ISSUE TITLE
ProcessException: The system cannot find the file specified.

### ISSUE THREAD

**Issue by ShohidulProgrammer** [lohanidamodar/flutter_automation#9]
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: keytool -genkey -noprompt -alias panj_pyare_app_key -dname "CN=test name OU=my organization O=organization name L=my location S=state C=+01" -keystore k
eys/keystore.jks -storepass somePass@! -keypass 123456 -keyalg RSA -keysize 2048 -validity 10000
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:476:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:619:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      _generateKeystore (package:flutter_automation/android_signing.dart:45:31)
#4      _androidSign (package:flutter_automation/android_signing.dart:11:3)
#5      decipherScript (package:flutter_automation/flutter_automation.dart:69:5)
#6      main (file:///E:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_automation-2.0.0/bin/flutt
er_automation.dart:4:3)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255

**Comment by sunilhari9** [comment]
Iam also getting similar issue after runing the command for build it is throwing
Execution failed for task ':app:validateSigningRelease'.
> Keystore file 'C:\Users\flutter\app\keys\keystore.jks' not found for signing config 'release'
